<?php
/**
 * ResponseModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KountRISSwaggerV02
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PhpApi\Khash;

use \ArrayAccess;
use \PhpApi\ObjectSerializer;

/**
 * ResponseModel Class Doc Comment
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseModel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ResponseModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ris_response' => 'string',
        'ris_vers' => 'string',
        'ris_mode' => 'string',
        'ris_merc' => 'string',
        'ris_sess' => 'string',
        'ris_ordr' => 'string',
        'ris_auto' => 'string',
        'ris_scor' => 'string',
        'ris_geox' => 'string',
        'ris_brnd' => 'string',
        'ris_regn' => 'string',
        'ris_netw' => 'string',
        'ris_kapt' => 'string',
        'ris_cards' => 'string',
        'ris_devices' => 'string',
        'ris_emails' => 'string',
        'ris_velo' => 'string',
        'ris_vmax' => 'string',
        'ris_site' => 'string',
        'ris_device_layers' => 'string',
        'ris_fingerprint' => 'string',
        'ris_timezone' => 'string',
        'ris_localtime' => 'string',
        'ris_region' => 'string',
        'ris_country' => 'string',
        'ris_proxy' => 'string',
        'ris_javascript' => 'string',
        'ris_flash' => 'string',
        'ris_cookies' => 'string',
        'ris_http_country' => 'string',
        'ris_language' => 'string',
        'ris_mobile_device' => 'string',
        'ris_mobile_type' => 'string',
        'ris_mobile_forwarder' => 'string',
        'ris_voice_device' => 'string',
        'ris_pc_remote' => 'string',
        'ris_rules_triggered' => 'string',
        'ris_counters_triggered' => 'string',
        'ris_reason_code' => 'string',
        'ris_ddfs' => 'string',
        'ris_dsr' => 'string',
        'ris_uas' => 'string',
        'ris_browser' => 'string',
        'ris_os' => 'string',
        'ris_pip_ipad' => 'string',
        'ris_pip_lat' => 'string',
        'ris_pip_lon' => 'string',
        'ris_pip_country' => 'string',
        'ris_pip_region' => 'string',
        'ris_pip_city' => 'string',
        'ris_pip_org' => 'string',
        'ris_ip_ipad' => 'string',
        'ris_ip_lat' => 'string',
        'ris_ip_lon' => 'string',
        'ris_ip_country' => 'string',
        'ris_ip_region' => 'string',
        'ris_ip_city' => 'string',
        'ris_ip_org' => 'string',
        'ris_warning_count' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ris_response' => null,
        'ris_vers' => null,
        'ris_mode' => null,
        'ris_merc' => null,
        'ris_sess' => null,
        'ris_ordr' => null,
        'ris_auto' => null,
        'ris_scor' => null,
        'ris_geox' => null,
        'ris_brnd' => null,
        'ris_regn' => null,
        'ris_netw' => null,
        'ris_kapt' => null,
        'ris_cards' => null,
        'ris_devices' => null,
        'ris_emails' => null,
        'ris_velo' => null,
        'ris_vmax' => null,
        'ris_site' => null,
        'ris_device_layers' => null,
        'ris_fingerprint' => null,
        'ris_timezone' => null,
        'ris_localtime' => null,
        'ris_region' => null,
        'ris_country' => null,
        'ris_proxy' => null,
        'ris_javascript' => null,
        'ris_flash' => null,
        'ris_cookies' => null,
        'ris_http_country' => null,
        'ris_language' => null,
        'ris_mobile_device' => null,
        'ris_mobile_type' => null,
        'ris_mobile_forwarder' => null,
        'ris_voice_device' => null,
        'ris_pc_remote' => null,
        'ris_rules_triggered' => null,
        'ris_counters_triggered' => null,
        'ris_reason_code' => null,
        'ris_ddfs' => null,
        'ris_dsr' => null,
        'ris_uas' => null,
        'ris_browser' => null,
        'ris_os' => null,
        'ris_pip_ipad' => null,
        'ris_pip_lat' => null,
        'ris_pip_lon' => null,
        'ris_pip_country' => null,
        'ris_pip_region' => null,
        'ris_pip_city' => null,
        'ris_pip_org' => null,
        'ris_ip_ipad' => null,
        'ris_ip_lat' => null,
        'ris_ip_lon' => null,
        'ris_ip_country' => null,
        'ris_ip_region' => null,
        'ris_ip_city' => null,
        'ris_ip_org' => null,
        'ris_warning_count' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ris_response' => 'RisResponse',
        'ris_vers' => 'risVERS',
        'ris_mode' => 'risMODE',
        'ris_merc' => 'risMERC',
        'ris_sess' => 'risSESS',
        'ris_ordr' => 'risORDR',
        'ris_auto' => 'risAUTO',
        'ris_scor' => 'risSCOR',
        'ris_geox' => 'risGEOX',
        'ris_brnd' => 'risBRND',
        'ris_regn' => 'risREGN',
        'ris_netw' => 'risNETW',
        'ris_kapt' => 'risKAPT',
        'ris_cards' => 'risCARDS',
        'ris_devices' => 'risDEVICES',
        'ris_emails' => 'risEMAILS',
        'ris_velo' => 'risVELO',
        'ris_vmax' => 'risVMAX',
        'ris_site' => 'risSITE',
        'ris_device_layers' => 'risDEVICE_LAYERS',
        'ris_fingerprint' => 'risFINGERPRINT',
        'ris_timezone' => 'risTIMEZONE',
        'ris_localtime' => 'risLOCALTIME',
        'ris_region' => 'risREGION',
        'ris_country' => 'risCOUNTRY',
        'ris_proxy' => 'risPROXY',
        'ris_javascript' => 'risJAVASCRIPT',
        'ris_flash' => 'risFLASH',
        'ris_cookies' => 'risCOOKIES',
        'ris_http_country' => 'risHTTP_COUNTRY',
        'ris_language' => 'risLANGUAGE',
        'ris_mobile_device' => 'risMOBILE_DEVICE',
        'ris_mobile_type' => 'risMOBILE_TYPE',
        'ris_mobile_forwarder' => 'risMOBILE_FORWARDER',
        'ris_voice_device' => 'risVOICE_DEVICE',
        'ris_pc_remote' => 'risPC_REMOTE',
        'ris_rules_triggered' => 'risRULES_TRIGGERED',
        'ris_counters_triggered' => 'risCOUNTERS_TRIGGERED',
        'ris_reason_code' => 'risREASON_CODE',
        'ris_ddfs' => 'risDDFS',
        'ris_dsr' => 'risDSR',
        'ris_uas' => 'risUAS',
        'ris_browser' => 'risBROWSER',
        'ris_os' => 'risOS',
        'ris_pip_ipad' => 'risPIP_IPAD',
        'ris_pip_lat' => 'risPIP_LAT',
        'ris_pip_lon' => 'risPIP_LON',
        'ris_pip_country' => 'risPIP_COUNTRY',
        'ris_pip_region' => 'risPIP_REGION',
        'ris_pip_city' => 'risPIP_CITY',
        'ris_pip_org' => 'risPIP_ORG',
        'ris_ip_ipad' => 'risIP_IPAD',
        'ris_ip_lat' => 'risIP_LAT',
        'ris_ip_lon' => 'risIP_LON',
        'ris_ip_country' => 'risIP_COUNTRY',
        'ris_ip_region' => 'risIP_REGION',
        'ris_ip_city' => 'risIP_CITY',
        'ris_ip_org' => 'risIP_ORG',
        'ris_warning_count' => 'risWARNING_COUNT'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ris_response' => 'setRisResponse',
        'ris_vers' => 'setRisVers',
        'ris_mode' => 'setRisMode',
        'ris_merc' => 'setRisMerc',
        'ris_sess' => 'setRisSess',
        'ris_ordr' => 'setRisOrdr',
        'ris_auto' => 'setRisAuto',
        'ris_scor' => 'setRisScor',
        'ris_geox' => 'setRisGeox',
        'ris_brnd' => 'setRisBrnd',
        'ris_regn' => 'setRisRegn',
        'ris_netw' => 'setRisNetw',
        'ris_kapt' => 'setRisKapt',
        'ris_cards' => 'setRisCards',
        'ris_devices' => 'setRisDevices',
        'ris_emails' => 'setRisEmails',
        'ris_velo' => 'setRisVelo',
        'ris_vmax' => 'setRisVmax',
        'ris_site' => 'setRisSite',
        'ris_device_layers' => 'setRisDeviceLayers',
        'ris_fingerprint' => 'setRisFingerprint',
        'ris_timezone' => 'setRisTimezone',
        'ris_localtime' => 'setRisLocaltime',
        'ris_region' => 'setRisRegion',
        'ris_country' => 'setRisCountry',
        'ris_proxy' => 'setRisProxy',
        'ris_javascript' => 'setRisJavascript',
        'ris_flash' => 'setRisFlash',
        'ris_cookies' => 'setRisCookies',
        'ris_http_country' => 'setRisHttpCountry',
        'ris_language' => 'setRisLanguage',
        'ris_mobile_device' => 'setRisMobileDevice',
        'ris_mobile_type' => 'setRisMobileType',
        'ris_mobile_forwarder' => 'setRisMobileForwarder',
        'ris_voice_device' => 'setRisVoiceDevice',
        'ris_pc_remote' => 'setRisPcRemote',
        'ris_rules_triggered' => 'setRisRulesTriggered',
        'ris_counters_triggered' => 'setRisCountersTriggered',
        'ris_reason_code' => 'setRisReasonCode',
        'ris_ddfs' => 'setRisDdfs',
        'ris_dsr' => 'setRisDsr',
        'ris_uas' => 'setRisUas',
        'ris_browser' => 'setRisBrowser',
        'ris_os' => 'setRisOs',
        'ris_pip_ipad' => 'setRisPipIpad',
        'ris_pip_lat' => 'setRisPipLat',
        'ris_pip_lon' => 'setRisPipLon',
        'ris_pip_country' => 'setRisPipCountry',
        'ris_pip_region' => 'setRisPipRegion',
        'ris_pip_city' => 'setRisPipCity',
        'ris_pip_org' => 'setRisPipOrg',
        'ris_ip_ipad' => 'setRisIpIpad',
        'ris_ip_lat' => 'setRisIpLat',
        'ris_ip_lon' => 'setRisIpLon',
        'ris_ip_country' => 'setRisIpCountry',
        'ris_ip_region' => 'setRisIpRegion',
        'ris_ip_city' => 'setRisIpCity',
        'ris_ip_org' => 'setRisIpOrg',
        'ris_warning_count' => 'setRisWarningCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ris_response' => 'getRisResponse',
        'ris_vers' => 'getRisVers',
        'ris_mode' => 'getRisMode',
        'ris_merc' => 'getRisMerc',
        'ris_sess' => 'getRisSess',
        'ris_ordr' => 'getRisOrdr',
        'ris_auto' => 'getRisAuto',
        'ris_scor' => 'getRisScor',
        'ris_geox' => 'getRisGeox',
        'ris_brnd' => 'getRisBrnd',
        'ris_regn' => 'getRisRegn',
        'ris_netw' => 'getRisNetw',
        'ris_kapt' => 'getRisKapt',
        'ris_cards' => 'getRisCards',
        'ris_devices' => 'getRisDevices',
        'ris_emails' => 'getRisEmails',
        'ris_velo' => 'getRisVelo',
        'ris_vmax' => 'getRisVmax',
        'ris_site' => 'getRisSite',
        'ris_device_layers' => 'getRisDeviceLayers',
        'ris_fingerprint' => 'getRisFingerprint',
        'ris_timezone' => 'getRisTimezone',
        'ris_localtime' => 'getRisLocaltime',
        'ris_region' => 'getRisRegion',
        'ris_country' => 'getRisCountry',
        'ris_proxy' => 'getRisProxy',
        'ris_javascript' => 'getRisJavascript',
        'ris_flash' => 'getRisFlash',
        'ris_cookies' => 'getRisCookies',
        'ris_http_country' => 'getRisHttpCountry',
        'ris_language' => 'getRisLanguage',
        'ris_mobile_device' => 'getRisMobileDevice',
        'ris_mobile_type' => 'getRisMobileType',
        'ris_mobile_forwarder' => 'getRisMobileForwarder',
        'ris_voice_device' => 'getRisVoiceDevice',
        'ris_pc_remote' => 'getRisPcRemote',
        'ris_rules_triggered' => 'getRisRulesTriggered',
        'ris_counters_triggered' => 'getRisCountersTriggered',
        'ris_reason_code' => 'getRisReasonCode',
        'ris_ddfs' => 'getRisDdfs',
        'ris_dsr' => 'getRisDsr',
        'ris_uas' => 'getRisUas',
        'ris_browser' => 'getRisBrowser',
        'ris_os' => 'getRisOs',
        'ris_pip_ipad' => 'getRisPipIpad',
        'ris_pip_lat' => 'getRisPipLat',
        'ris_pip_lon' => 'getRisPipLon',
        'ris_pip_country' => 'getRisPipCountry',
        'ris_pip_region' => 'getRisPipRegion',
        'ris_pip_city' => 'getRisPipCity',
        'ris_pip_org' => 'getRisPipOrg',
        'ris_ip_ipad' => 'getRisIpIpad',
        'ris_ip_lat' => 'getRisIpLat',
        'ris_ip_lon' => 'getRisIpLon',
        'ris_ip_country' => 'getRisIpCountry',
        'ris_ip_region' => 'getRisIpRegion',
        'ris_ip_city' => 'getRisIpCity',
        'ris_ip_org' => 'getRisIpOrg',
        'ris_warning_count' => 'getRisWarningCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ris_response'] = isset($data['ris_response']) ? $data['ris_response'] : null;
        $this->container['ris_vers'] = isset($data['ris_vers']) ? $data['ris_vers'] : null;
        $this->container['ris_mode'] = isset($data['ris_mode']) ? $data['ris_mode'] : null;
        $this->container['ris_merc'] = isset($data['ris_merc']) ? $data['ris_merc'] : null;
        $this->container['ris_sess'] = isset($data['ris_sess']) ? $data['ris_sess'] : null;
        $this->container['ris_ordr'] = isset($data['ris_ordr']) ? $data['ris_ordr'] : null;
        $this->container['ris_auto'] = isset($data['ris_auto']) ? $data['ris_auto'] : null;
        $this->container['ris_scor'] = isset($data['ris_scor']) ? $data['ris_scor'] : null;
        $this->container['ris_geox'] = isset($data['ris_geox']) ? $data['ris_geox'] : null;
        $this->container['ris_brnd'] = isset($data['ris_brnd']) ? $data['ris_brnd'] : null;
        $this->container['ris_regn'] = isset($data['ris_regn']) ? $data['ris_regn'] : null;
        $this->container['ris_netw'] = isset($data['ris_netw']) ? $data['ris_netw'] : null;
        $this->container['ris_kapt'] = isset($data['ris_kapt']) ? $data['ris_kapt'] : null;
        $this->container['ris_cards'] = isset($data['ris_cards']) ? $data['ris_cards'] : null;
        $this->container['ris_devices'] = isset($data['ris_devices']) ? $data['ris_devices'] : null;
        $this->container['ris_emails'] = isset($data['ris_emails']) ? $data['ris_emails'] : null;
        $this->container['ris_velo'] = isset($data['ris_velo']) ? $data['ris_velo'] : null;
        $this->container['ris_vmax'] = isset($data['ris_vmax']) ? $data['ris_vmax'] : null;
        $this->container['ris_site'] = isset($data['ris_site']) ? $data['ris_site'] : null;
        $this->container['ris_device_layers'] = isset($data['ris_device_layers']) ? $data['ris_device_layers'] : null;
        $this->container['ris_fingerprint'] = isset($data['ris_fingerprint']) ? $data['ris_fingerprint'] : null;
        $this->container['ris_timezone'] = isset($data['ris_timezone']) ? $data['ris_timezone'] : null;
        $this->container['ris_localtime'] = isset($data['ris_localtime']) ? $data['ris_localtime'] : null;
        $this->container['ris_region'] = isset($data['ris_region']) ? $data['ris_region'] : null;
        $this->container['ris_country'] = isset($data['ris_country']) ? $data['ris_country'] : null;
        $this->container['ris_proxy'] = isset($data['ris_proxy']) ? $data['ris_proxy'] : null;
        $this->container['ris_javascript'] = isset($data['ris_javascript']) ? $data['ris_javascript'] : null;
        $this->container['ris_flash'] = isset($data['ris_flash']) ? $data['ris_flash'] : null;
        $this->container['ris_cookies'] = isset($data['ris_cookies']) ? $data['ris_cookies'] : null;
        $this->container['ris_http_country'] = isset($data['ris_http_country']) ? $data['ris_http_country'] : null;
        $this->container['ris_language'] = isset($data['ris_language']) ? $data['ris_language'] : null;
        $this->container['ris_mobile_device'] = isset($data['ris_mobile_device']) ? $data['ris_mobile_device'] : null;
        $this->container['ris_mobile_type'] = isset($data['ris_mobile_type']) ? $data['ris_mobile_type'] : null;
        $this->container['ris_mobile_forwarder'] = isset($data['ris_mobile_forwarder']) ? $data['ris_mobile_forwarder'] : null;
        $this->container['ris_voice_device'] = isset($data['ris_voice_device']) ? $data['ris_voice_device'] : null;
        $this->container['ris_pc_remote'] = isset($data['ris_pc_remote']) ? $data['ris_pc_remote'] : null;
        $this->container['ris_rules_triggered'] = isset($data['ris_rules_triggered']) ? $data['ris_rules_triggered'] : null;
        $this->container['ris_counters_triggered'] = isset($data['ris_counters_triggered']) ? $data['ris_counters_triggered'] : null;
        $this->container['ris_reason_code'] = isset($data['ris_reason_code']) ? $data['ris_reason_code'] : null;
        $this->container['ris_ddfs'] = isset($data['ris_ddfs']) ? $data['ris_ddfs'] : null;
        $this->container['ris_dsr'] = isset($data['ris_dsr']) ? $data['ris_dsr'] : null;
        $this->container['ris_uas'] = isset($data['ris_uas']) ? $data['ris_uas'] : null;
        $this->container['ris_browser'] = isset($data['ris_browser']) ? $data['ris_browser'] : null;
        $this->container['ris_os'] = isset($data['ris_os']) ? $data['ris_os'] : null;
        $this->container['ris_pip_ipad'] = isset($data['ris_pip_ipad']) ? $data['ris_pip_ipad'] : null;
        $this->container['ris_pip_lat'] = isset($data['ris_pip_lat']) ? $data['ris_pip_lat'] : null;
        $this->container['ris_pip_lon'] = isset($data['ris_pip_lon']) ? $data['ris_pip_lon'] : null;
        $this->container['ris_pip_country'] = isset($data['ris_pip_country']) ? $data['ris_pip_country'] : null;
        $this->container['ris_pip_region'] = isset($data['ris_pip_region']) ? $data['ris_pip_region'] : null;
        $this->container['ris_pip_city'] = isset($data['ris_pip_city']) ? $data['ris_pip_city'] : null;
        $this->container['ris_pip_org'] = isset($data['ris_pip_org']) ? $data['ris_pip_org'] : null;
        $this->container['ris_ip_ipad'] = isset($data['ris_ip_ipad']) ? $data['ris_ip_ipad'] : null;
        $this->container['ris_ip_lat'] = isset($data['ris_ip_lat']) ? $data['ris_ip_lat'] : null;
        $this->container['ris_ip_lon'] = isset($data['ris_ip_lon']) ? $data['ris_ip_lon'] : null;
        $this->container['ris_ip_country'] = isset($data['ris_ip_country']) ? $data['ris_ip_country'] : null;
        $this->container['ris_ip_region'] = isset($data['ris_ip_region']) ? $data['ris_ip_region'] : null;
        $this->container['ris_ip_city'] = isset($data['ris_ip_city']) ? $data['ris_ip_city'] : null;
        $this->container['ris_ip_org'] = isset($data['ris_ip_org']) ? $data['ris_ip_org'] : null;
        $this->container['ris_warning_count'] = isset($data['ris_warning_count']) ? $data['ris_warning_count'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ris_response
     *
     * @return string
     */
    public function getRisResponse()
    {
        return $this->container['ris_response'];
    }

    /**
     * Sets ris_response
     *
     * @param string $ris_response ris_response
     *
     * @return $this
     */
    public function setRisResponse($ris_response)
    {
        $this->container['ris_response'] = $ris_response;

        return $this;
    }

    /**
     * Gets ris_vers
     *
     * @return string
     */
    public function getRisVers()
    {
        return $this->container['ris_vers'];
    }

    /**
     * Sets ris_vers
     *
     * @param string $ris_vers ris_vers
     *
     * @return $this
     */
    public function setRisVers($ris_vers)
    {
        $this->container['ris_vers'] = $ris_vers;

        return $this;
    }

    /**
     * Gets ris_mode
     *
     * @return string
     */
    public function getRisMode()
    {
        return $this->container['ris_mode'];
    }

    /**
     * Sets ris_mode
     *
     * @param string $ris_mode ris_mode
     *
     * @return $this
     */
    public function setRisMode($ris_mode)
    {
        $this->container['ris_mode'] = $ris_mode;

        return $this;
    }

    /**
     * Gets ris_merc
     *
     * @return string
     */
    public function getRisMerc()
    {
        return $this->container['ris_merc'];
    }

    /**
     * Sets ris_merc
     *
     * @param string $ris_merc ris_merc
     *
     * @return $this
     */
    public function setRisMerc($ris_merc)
    {
        $this->container['ris_merc'] = $ris_merc;

        return $this;
    }

    /**
     * Gets ris_sess
     *
     * @return string
     */
    public function getRisSess()
    {
        return $this->container['ris_sess'];
    }

    /**
     * Sets ris_sess
     *
     * @param string $ris_sess ris_sess
     *
     * @return $this
     */
    public function setRisSess($ris_sess)
    {
        $this->container['ris_sess'] = $ris_sess;

        return $this;
    }

    /**
     * Gets ris_ordr
     *
     * @return string
     */
    public function getRisOrdr()
    {
        return $this->container['ris_ordr'];
    }

    /**
     * Sets ris_ordr
     *
     * @param string $ris_ordr ris_ordr
     *
     * @return $this
     */
    public function setRisOrdr($ris_ordr)
    {
        $this->container['ris_ordr'] = $ris_ordr;

        return $this;
    }

    /**
     * Gets ris_auto
     *
     * @return string
     */
    public function getRisAuto()
    {
        return $this->container['ris_auto'];
    }

    /**
     * Sets ris_auto
     *
     * @param string $ris_auto ris_auto
     *
     * @return $this
     */
    public function setRisAuto($ris_auto)
    {
        $this->container['ris_auto'] = $ris_auto;

        return $this;
    }

    /**
     * Gets ris_scor
     *
     * @return string
     */
    public function getRisScor()
    {
        return $this->container['ris_scor'];
    }

    /**
     * Sets ris_scor
     *
     * @param string $ris_scor ris_scor
     *
     * @return $this
     */
    public function setRisScor($ris_scor)
    {
        $this->container['ris_scor'] = $ris_scor;

        return $this;
    }

    /**
     * Gets ris_geox
     *
     * @return string
     */
    public function getRisGeox()
    {
        return $this->container['ris_geox'];
    }

    /**
     * Sets ris_geox
     *
     * @param string $ris_geox ris_geox
     *
     * @return $this
     */
    public function setRisGeox($ris_geox)
    {
        $this->container['ris_geox'] = $ris_geox;

        return $this;
    }

    /**
     * Gets ris_brnd
     *
     * @return string
     */
    public function getRisBrnd()
    {
        return $this->container['ris_brnd'];
    }

    /**
     * Sets ris_brnd
     *
     * @param string $ris_brnd ris_brnd
     *
     * @return $this
     */
    public function setRisBrnd($ris_brnd)
    {
        $this->container['ris_brnd'] = $ris_brnd;

        return $this;
    }

    /**
     * Gets ris_regn
     *
     * @return string
     */
    public function getRisRegn()
    {
        return $this->container['ris_regn'];
    }

    /**
     * Sets ris_regn
     *
     * @param string $ris_regn ris_regn
     *
     * @return $this
     */
    public function setRisRegn($ris_regn)
    {
        $this->container['ris_regn'] = $ris_regn;

        return $this;
    }

    /**
     * Gets ris_netw
     *
     * @return string
     */
    public function getRisNetw()
    {
        return $this->container['ris_netw'];
    }

    /**
     * Sets ris_netw
     *
     * @param string $ris_netw ris_netw
     *
     * @return $this
     */
    public function setRisNetw($ris_netw)
    {
        $this->container['ris_netw'] = $ris_netw;

        return $this;
    }

    /**
     * Gets ris_kapt
     *
     * @return string
     */
    public function getRisKapt()
    {
        return $this->container['ris_kapt'];
    }

    /**
     * Sets ris_kapt
     *
     * @param string $ris_kapt ris_kapt
     *
     * @return $this
     */
    public function setRisKapt($ris_kapt)
    {
        $this->container['ris_kapt'] = $ris_kapt;

        return $this;
    }

    /**
     * Gets ris_cards
     *
     * @return string
     */
    public function getRisCards()
    {
        return $this->container['ris_cards'];
    }

    /**
     * Sets ris_cards
     *
     * @param string $ris_cards ris_cards
     *
     * @return $this
     */
    public function setRisCards($ris_cards)
    {
        $this->container['ris_cards'] = $ris_cards;

        return $this;
    }

    /**
     * Gets ris_devices
     *
     * @return string
     */
    public function getRisDevices()
    {
        return $this->container['ris_devices'];
    }

    /**
     * Sets ris_devices
     *
     * @param string $ris_devices ris_devices
     *
     * @return $this
     */
    public function setRisDevices($ris_devices)
    {
        $this->container['ris_devices'] = $ris_devices;

        return $this;
    }

    /**
     * Gets ris_emails
     *
     * @return string
     */
    public function getRisEmails()
    {
        return $this->container['ris_emails'];
    }

    /**
     * Sets ris_emails
     *
     * @param string $ris_emails ris_emails
     *
     * @return $this
     */
    public function setRisEmails($ris_emails)
    {
        $this->container['ris_emails'] = $ris_emails;

        return $this;
    }

    /**
     * Gets ris_velo
     *
     * @return string
     */
    public function getRisVelo()
    {
        return $this->container['ris_velo'];
    }

    /**
     * Sets ris_velo
     *
     * @param string $ris_velo ris_velo
     *
     * @return $this
     */
    public function setRisVelo($ris_velo)
    {
        $this->container['ris_velo'] = $ris_velo;

        return $this;
    }

    /**
     * Gets ris_vmax
     *
     * @return string
     */
    public function getRisVmax()
    {
        return $this->container['ris_vmax'];
    }

    /**
     * Sets ris_vmax
     *
     * @param string $ris_vmax ris_vmax
     *
     * @return $this
     */
    public function setRisVmax($ris_vmax)
    {
        $this->container['ris_vmax'] = $ris_vmax;

        return $this;
    }

    /**
     * Gets ris_site
     *
     * @return string
     */
    public function getRisSite()
    {
        return $this->container['ris_site'];
    }

    /**
     * Sets ris_site
     *
     * @param string $ris_site ris_site
     *
     * @return $this
     */
    public function setRisSite($ris_site)
    {
        $this->container['ris_site'] = $ris_site;

        return $this;
    }

    /**
     * Gets ris_device_layers
     *
     * @return string
     */
    public function getRisDeviceLayers()
    {
        return $this->container['ris_device_layers'];
    }

    /**
     * Sets ris_device_layers
     *
     * @param string $ris_device_layers ris_device_layers
     *
     * @return $this
     */
    public function setRisDeviceLayers($ris_device_layers)
    {
        $this->container['ris_device_layers'] = $ris_device_layers;

        return $this;
    }

    /**
     * Gets ris_fingerprint
     *
     * @return string
     */
    public function getRisFingerprint()
    {
        return $this->container['ris_fingerprint'];
    }

    /**
     * Sets ris_fingerprint
     *
     * @param string $ris_fingerprint ris_fingerprint
     *
     * @return $this
     */
    public function setRisFingerprint($ris_fingerprint)
    {
        $this->container['ris_fingerprint'] = $ris_fingerprint;

        return $this;
    }

    /**
     * Gets ris_timezone
     *
     * @return string
     */
    public function getRisTimezone()
    {
        return $this->container['ris_timezone'];
    }

    /**
     * Sets ris_timezone
     *
     * @param string $ris_timezone ris_timezone
     *
     * @return $this
     */
    public function setRisTimezone($ris_timezone)
    {
        $this->container['ris_timezone'] = $ris_timezone;

        return $this;
    }

    /**
     * Gets ris_localtime
     *
     * @return string
     */
    public function getRisLocaltime()
    {
        return $this->container['ris_localtime'];
    }

    /**
     * Sets ris_localtime
     *
     * @param string $ris_localtime ris_localtime
     *
     * @return $this
     */
    public function setRisLocaltime($ris_localtime)
    {
        $this->container['ris_localtime'] = $ris_localtime;

        return $this;
    }

    /**
     * Gets ris_region
     *
     * @return string
     */
    public function getRisRegion()
    {
        return $this->container['ris_region'];
    }

    /**
     * Sets ris_region
     *
     * @param string $ris_region ris_region
     *
     * @return $this
     */
    public function setRisRegion($ris_region)
    {
        $this->container['ris_region'] = $ris_region;

        return $this;
    }

    /**
     * Gets ris_country
     *
     * @return string
     */
    public function getRisCountry()
    {
        return $this->container['ris_country'];
    }

    /**
     * Sets ris_country
     *
     * @param string $ris_country ris_country
     *
     * @return $this
     */
    public function setRisCountry($ris_country)
    {
        $this->container['ris_country'] = $ris_country;

        return $this;
    }

    /**
     * Gets ris_proxy
     *
     * @return string
     */
    public function getRisProxy()
    {
        return $this->container['ris_proxy'];
    }

    /**
     * Sets ris_proxy
     *
     * @param string $ris_proxy ris_proxy
     *
     * @return $this
     */
    public function setRisProxy($ris_proxy)
    {
        $this->container['ris_proxy'] = $ris_proxy;

        return $this;
    }

    /**
     * Gets ris_javascript
     *
     * @return string
     */
    public function getRisJavascript()
    {
        return $this->container['ris_javascript'];
    }

    /**
     * Sets ris_javascript
     *
     * @param string $ris_javascript ris_javascript
     *
     * @return $this
     */
    public function setRisJavascript($ris_javascript)
    {
        $this->container['ris_javascript'] = $ris_javascript;

        return $this;
    }

    /**
     * Gets ris_flash
     *
     * @return string
     */
    public function getRisFlash()
    {
        return $this->container['ris_flash'];
    }

    /**
     * Sets ris_flash
     *
     * @param string $ris_flash ris_flash
     *
     * @return $this
     */
    public function setRisFlash($ris_flash)
    {
        $this->container['ris_flash'] = $ris_flash;

        return $this;
    }

    /**
     * Gets ris_cookies
     *
     * @return string
     */
    public function getRisCookies()
    {
        return $this->container['ris_cookies'];
    }

    /**
     * Sets ris_cookies
     *
     * @param string $ris_cookies ris_cookies
     *
     * @return $this
     */
    public function setRisCookies($ris_cookies)
    {
        $this->container['ris_cookies'] = $ris_cookies;

        return $this;
    }

    /**
     * Gets ris_http_country
     *
     * @return string
     */
    public function getRisHttpCountry()
    {
        return $this->container['ris_http_country'];
    }

    /**
     * Sets ris_http_country
     *
     * @param string $ris_http_country ris_http_country
     *
     * @return $this
     */
    public function setRisHttpCountry($ris_http_country)
    {
        $this->container['ris_http_country'] = $ris_http_country;

        return $this;
    }

    /**
     * Gets ris_language
     *
     * @return string
     */
    public function getRisLanguage()
    {
        return $this->container['ris_language'];
    }

    /**
     * Sets ris_language
     *
     * @param string $ris_language ris_language
     *
     * @return $this
     */
    public function setRisLanguage($ris_language)
    {
        $this->container['ris_language'] = $ris_language;

        return $this;
    }

    /**
     * Gets ris_mobile_device
     *
     * @return string
     */
    public function getRisMobileDevice()
    {
        return $this->container['ris_mobile_device'];
    }

    /**
     * Sets ris_mobile_device
     *
     * @param string $ris_mobile_device ris_mobile_device
     *
     * @return $this
     */
    public function setRisMobileDevice($ris_mobile_device)
    {
        $this->container['ris_mobile_device'] = $ris_mobile_device;

        return $this;
    }

    /**
     * Gets ris_mobile_type
     *
     * @return string
     */
    public function getRisMobileType()
    {
        return $this->container['ris_mobile_type'];
    }

    /**
     * Sets ris_mobile_type
     *
     * @param string $ris_mobile_type ris_mobile_type
     *
     * @return $this
     */
    public function setRisMobileType($ris_mobile_type)
    {
        $this->container['ris_mobile_type'] = $ris_mobile_type;

        return $this;
    }

    /**
     * Gets ris_mobile_forwarder
     *
     * @return string
     */
    public function getRisMobileForwarder()
    {
        return $this->container['ris_mobile_forwarder'];
    }

    /**
     * Sets ris_mobile_forwarder
     *
     * @param string $ris_mobile_forwarder ris_mobile_forwarder
     *
     * @return $this
     */
    public function setRisMobileForwarder($ris_mobile_forwarder)
    {
        $this->container['ris_mobile_forwarder'] = $ris_mobile_forwarder;

        return $this;
    }

    /**
     * Gets ris_voice_device
     *
     * @return string
     */
    public function getRisVoiceDevice()
    {
        return $this->container['ris_voice_device'];
    }

    /**
     * Sets ris_voice_device
     *
     * @param string $ris_voice_device ris_voice_device
     *
     * @return $this
     */
    public function setRisVoiceDevice($ris_voice_device)
    {
        $this->container['ris_voice_device'] = $ris_voice_device;

        return $this;
    }

    /**
     * Gets ris_pc_remote
     *
     * @return string
     */
    public function getRisPcRemote()
    {
        return $this->container['ris_pc_remote'];
    }

    /**
     * Sets ris_pc_remote
     *
     * @param string $ris_pc_remote ris_pc_remote
     *
     * @return $this
     */
    public function setRisPcRemote($ris_pc_remote)
    {
        $this->container['ris_pc_remote'] = $ris_pc_remote;

        return $this;
    }

    /**
     * Gets ris_rules_triggered
     *
     * @return string
     */
    public function getRisRulesTriggered()
    {
        return $this->container['ris_rules_triggered'];
    }

    /**
     * Sets ris_rules_triggered
     *
     * @param string $ris_rules_triggered ris_rules_triggered
     *
     * @return $this
     */
    public function setRisRulesTriggered($ris_rules_triggered)
    {
        $this->container['ris_rules_triggered'] = $ris_rules_triggered;

        return $this;
    }

    /**
     * Gets ris_counters_triggered
     *
     * @return string
     */
    public function getRisCountersTriggered()
    {
        return $this->container['ris_counters_triggered'];
    }

    /**
     * Sets ris_counters_triggered
     *
     * @param string $ris_counters_triggered ris_counters_triggered
     *
     * @return $this
     */
    public function setRisCountersTriggered($ris_counters_triggered)
    {
        $this->container['ris_counters_triggered'] = $ris_counters_triggered;

        return $this;
    }

    /**
     * Gets ris_reason_code
     *
     * @return string
     */
    public function getRisReasonCode()
    {
        return $this->container['ris_reason_code'];
    }

    /**
     * Sets ris_reason_code
     *
     * @param string $ris_reason_code ris_reason_code
     *
     * @return $this
     */
    public function setRisReasonCode($ris_reason_code)
    {
        $this->container['ris_reason_code'] = $ris_reason_code;

        return $this;
    }

    /**
     * Gets ris_ddfs
     *
     * @return string
     */
    public function getRisDdfs()
    {
        return $this->container['ris_ddfs'];
    }

    /**
     * Sets ris_ddfs
     *
     * @param string $ris_ddfs ris_ddfs
     *
     * @return $this
     */
    public function setRisDdfs($ris_ddfs)
    {
        $this->container['ris_ddfs'] = $ris_ddfs;

        return $this;
    }

    /**
     * Gets ris_dsr
     *
     * @return string
     */
    public function getRisDsr()
    {
        return $this->container['ris_dsr'];
    }

    /**
     * Sets ris_dsr
     *
     * @param string $ris_dsr ris_dsr
     *
     * @return $this
     */
    public function setRisDsr($ris_dsr)
    {
        $this->container['ris_dsr'] = $ris_dsr;

        return $this;
    }

    /**
     * Gets ris_uas
     *
     * @return string
     */
    public function getRisUas()
    {
        return $this->container['ris_uas'];
    }

    /**
     * Sets ris_uas
     *
     * @param string $ris_uas ris_uas
     *
     * @return $this
     */
    public function setRisUas($ris_uas)
    {
        $this->container['ris_uas'] = $ris_uas;

        return $this;
    }

    /**
     * Gets ris_browser
     *
     * @return string
     */
    public function getRisBrowser()
    {
        return $this->container['ris_browser'];
    }

    /**
     * Sets ris_browser
     *
     * @param string $ris_browser ris_browser
     *
     * @return $this
     */
    public function setRisBrowser($ris_browser)
    {
        $this->container['ris_browser'] = $ris_browser;

        return $this;
    }

    /**
     * Gets ris_os
     *
     * @return string
     */
    public function getRisOs()
    {
        return $this->container['ris_os'];
    }

    /**
     * Sets ris_os
     *
     * @param string $ris_os ris_os
     *
     * @return $this
     */
    public function setRisOs($ris_os)
    {
        $this->container['ris_os'] = $ris_os;

        return $this;
    }

    /**
     * Gets ris_pip_ipad
     *
     * @return string
     */
    public function getRisPipIpad()
    {
        return $this->container['ris_pip_ipad'];
    }

    /**
     * Sets ris_pip_ipad
     *
     * @param string $ris_pip_ipad ris_pip_ipad
     *
     * @return $this
     */
    public function setRisPipIpad($ris_pip_ipad)
    {
        $this->container['ris_pip_ipad'] = $ris_pip_ipad;

        return $this;
    }

    /**
     * Gets ris_pip_lat
     *
     * @return string
     */
    public function getRisPipLat()
    {
        return $this->container['ris_pip_lat'];
    }

    /**
     * Sets ris_pip_lat
     *
     * @param string $ris_pip_lat ris_pip_lat
     *
     * @return $this
     */
    public function setRisPipLat($ris_pip_lat)
    {
        $this->container['ris_pip_lat'] = $ris_pip_lat;

        return $this;
    }

    /**
     * Gets ris_pip_lon
     *
     * @return string
     */
    public function getRisPipLon()
    {
        return $this->container['ris_pip_lon'];
    }

    /**
     * Sets ris_pip_lon
     *
     * @param string $ris_pip_lon ris_pip_lon
     *
     * @return $this
     */
    public function setRisPipLon($ris_pip_lon)
    {
        $this->container['ris_pip_lon'] = $ris_pip_lon;

        return $this;
    }

    /**
     * Gets ris_pip_country
     *
     * @return string
     */
    public function getRisPipCountry()
    {
        return $this->container['ris_pip_country'];
    }

    /**
     * Sets ris_pip_country
     *
     * @param string $ris_pip_country ris_pip_country
     *
     * @return $this
     */
    public function setRisPipCountry($ris_pip_country)
    {
        $this->container['ris_pip_country'] = $ris_pip_country;

        return $this;
    }

    /**
     * Gets ris_pip_region
     *
     * @return string
     */
    public function getRisPipRegion()
    {
        return $this->container['ris_pip_region'];
    }

    /**
     * Sets ris_pip_region
     *
     * @param string $ris_pip_region ris_pip_region
     *
     * @return $this
     */
    public function setRisPipRegion($ris_pip_region)
    {
        $this->container['ris_pip_region'] = $ris_pip_region;

        return $this;
    }

    /**
     * Gets ris_pip_city
     *
     * @return string
     */
    public function getRisPipCity()
    {
        return $this->container['ris_pip_city'];
    }

    /**
     * Sets ris_pip_city
     *
     * @param string $ris_pip_city ris_pip_city
     *
     * @return $this
     */
    public function setRisPipCity($ris_pip_city)
    {
        $this->container['ris_pip_city'] = $ris_pip_city;

        return $this;
    }

    /**
     * Gets ris_pip_org
     *
     * @return string
     */
    public function getRisPipOrg()
    {
        return $this->container['ris_pip_org'];
    }

    /**
     * Sets ris_pip_org
     *
     * @param string $ris_pip_org ris_pip_org
     *
     * @return $this
     */
    public function setRisPipOrg($ris_pip_org)
    {
        $this->container['ris_pip_org'] = $ris_pip_org;

        return $this;
    }

    /**
     * Gets ris_ip_ipad
     *
     * @return string
     */
    public function getRisIpIpad()
    {
        return $this->container['ris_ip_ipad'];
    }

    /**
     * Sets ris_ip_ipad
     *
     * @param string $ris_ip_ipad ris_ip_ipad
     *
     * @return $this
     */
    public function setRisIpIpad($ris_ip_ipad)
    {
        $this->container['ris_ip_ipad'] = $ris_ip_ipad;

        return $this;
    }

    /**
     * Gets ris_ip_lat
     *
     * @return string
     */
    public function getRisIpLat()
    {
        return $this->container['ris_ip_lat'];
    }

    /**
     * Sets ris_ip_lat
     *
     * @param string $ris_ip_lat ris_ip_lat
     *
     * @return $this
     */
    public function setRisIpLat($ris_ip_lat)
    {
        $this->container['ris_ip_lat'] = $ris_ip_lat;

        return $this;
    }

    /**
     * Gets ris_ip_lon
     *
     * @return string
     */
    public function getRisIpLon()
    {
        return $this->container['ris_ip_lon'];
    }

    /**
     * Sets ris_ip_lon
     *
     * @param string $ris_ip_lon ris_ip_lon
     *
     * @return $this
     */
    public function setRisIpLon($ris_ip_lon)
    {
        $this->container['ris_ip_lon'] = $ris_ip_lon;

        return $this;
    }

    /**
     * Gets ris_ip_country
     *
     * @return string
     */
    public function getRisIpCountry()
    {
        return $this->container['ris_ip_country'];
    }

    /**
     * Sets ris_ip_country
     *
     * @param string $ris_ip_country ris_ip_country
     *
     * @return $this
     */
    public function setRisIpCountry($ris_ip_country)
    {
        $this->container['ris_ip_country'] = $ris_ip_country;

        return $this;
    }

    /**
     * Gets ris_ip_region
     *
     * @return string
     */
    public function getRisIpRegion()
    {
        return $this->container['ris_ip_region'];
    }

    /**
     * Sets ris_ip_region
     *
     * @param string $ris_ip_region ris_ip_region
     *
     * @return $this
     */
    public function setRisIpRegion($ris_ip_region)
    {
        $this->container['ris_ip_region'] = $ris_ip_region;

        return $this;
    }

    /**
     * Gets ris_ip_city
     *
     * @return string
     */
    public function getRisIpCity()
    {
        return $this->container['ris_ip_city'];
    }

    /**
     * Sets ris_ip_city
     *
     * @param string $ris_ip_city ris_ip_city
     *
     * @return $this
     */
    public function setRisIpCity($ris_ip_city)
    {
        $this->container['ris_ip_city'] = $ris_ip_city;

        return $this;
    }

    /**
     * Gets ris_ip_org
     *
     * @return string
     */
    public function getRisIpOrg()
    {
        return $this->container['ris_ip_org'];
    }

    /**
     * Sets ris_ip_org
     *
     * @param string $ris_ip_org ris_ip_org
     *
     * @return $this
     */
    public function setRisIpOrg($ris_ip_org)
    {
        $this->container['ris_ip_org'] = $ris_ip_org;

        return $this;
    }

    /**
     * Gets ris_warning_count
     *
     * @return string
     */
    public function getRisWarningCount()
    {
        return $this->container['ris_warning_count'];
    }

    /**
     * Sets ris_warning_count
     *
     * @param string $ris_warning_count ris_warning_count
     *
     * @return $this
     */
    public function setRisWarningCount($ris_warning_count)
    {
        $this->container['ris_warning_count'] = $ris_warning_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


