<?php
/**
 * BillingAddressWithPremiseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KountRISSwaggerV02
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PhpApi;

/**
 * BillingAddressWithPremiseTest Class Doc Comment
 *
 * @category    Class
 * @description BillingAddressWithPremise
 * @package     PhpApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BillingAddressWithPremiseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BillingAddressWithPremise"
     */
    public function testBillingAddressWithPremise()
    {
    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {
    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "premise"
     */
    public function testPropertyPremise()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }
}
