<?php
/**
 * CartItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KountRISSwaggerV02
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PhpApi;

/**
 * CartItemTest Class Doc Comment
 *
 * @category    Class
 * @description Shopping cart item data object.&lt;br /&gt;&lt;b&gt;Author:&lt;/b&gt; Kount &lt;a&gt;custserv@kount.com&lt;/a&gt;;&lt;br /&gt;&lt;b&gt;Version:&lt;/b&gt; 7.0.0. &lt;br /&gt;&lt;b&gt;Copyright:&lt;/b&gt; 2010 Keynetics Inc &lt;br /&gt;
 * @package     PhpApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CartItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CartItem"
     */
    public function testCartItem()
    {
    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "product_item"
     */
    public function testPropertyProductItem()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "product_quantity"
     */
    public function testPropertyProductQuantity()
    {
    }

    /**
     * Test attribute "product_price"
     */
    public function testPropertyProductPrice()
    {
    }
}
