<?php
/**
 * InquiryModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KountRISSwaggerV02
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PhpApi;

/**
 * InquiryModelTest Class Doc Comment
 *
 * @category    Class
 * @description InquiryModel
 * @package     PhpApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InquiryModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InquiryModel"
     */
    public function testInquiryModel()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "date_of_birth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "sdk_version"
     */
    public function testPropertySdkVersion()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "user_agent"
     */
    public function testPropertyUserAgent()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "unique"
     */
    public function testPropertyUnique()
    {
    }

    /**
     * Test attribute "set_epoch"
     */
    public function testPropertySetEpoch()
    {
    }

    /**
     * Test attribute "cash"
     */
    public function testPropertyCash()
    {
    }

    /**
     * Test attribute "ship_type"
     */
    public function testPropertyShipType()
    {
    }

    /**
     * Test attribute "billing_phone_number"
     */
    public function testPropertyBillingPhoneNumber()
    {
    }

    /**
     * Test attribute "shipping_phone_number"
     */
    public function testPropertyShippingPhoneNumber()
    {
    }

    /**
     * Test attribute "shipping_name"
     */
    public function testPropertyShippingName()
    {
    }

    /**
     * Test attribute "shipping_email"
     */
    public function testPropertyShippingEmail()
    {
    }

    /**
     * Test attribute "anid"
     */
    public function testPropertyAnid()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "card_no"
     */
    public function testPropertyCardNo()
    {
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "mack"
     */
    public function testPropertyMack()
    {
    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "product_item"
     */
    public function testPropertyProductItem()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "product_quantity"
     */
    public function testPropertyProductQuantity()
    {
    }

    /**
     * Test attribute "product_price"
     */
    public function testPropertyProductPrice()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "cart"
     */
    public function testPropertyCart()
    {
    }

    /**
     * Test attribute "cart_item"
     */
    public function testPropertyCartItem()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "user_defined_field"
     */
    public function testPropertyUserDefinedField()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
    }

    /**
     * Test attribute "config_key"
     */
    public function testPropertyConfigKey()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }
}
