<?php
/**
 * ResponseModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KountRISSwaggerV02
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PhpApi;

/**
 * ResponseModelTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseModel
 * @package     PhpApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseModel"
     */
    public function testResponseModel()
    {
    }

    /**
     * Test attribute "ris_response"
     */
    public function testPropertyRisResponse()
    {
    }

    /**
     * Test attribute "ris_vers"
     */
    public function testPropertyRisVers()
    {
    }

    /**
     * Test attribute "ris_mode"
     */
    public function testPropertyRisMode()
    {
    }

    /**
     * Test attribute "ris_merc"
     */
    public function testPropertyRisMerc()
    {
    }

    /**
     * Test attribute "ris_sess"
     */
    public function testPropertyRisSess()
    {
    }

    /**
     * Test attribute "ris_ordr"
     */
    public function testPropertyRisOrdr()
    {
    }

    /**
     * Test attribute "ris_auto"
     */
    public function testPropertyRisAuto()
    {
    }

    /**
     * Test attribute "ris_scor"
     */
    public function testPropertyRisScor()
    {
    }

    /**
     * Test attribute "ris_geox"
     */
    public function testPropertyRisGeox()
    {
    }

    /**
     * Test attribute "ris_brnd"
     */
    public function testPropertyRisBrnd()
    {
    }

    /**
     * Test attribute "ris_regn"
     */
    public function testPropertyRisRegn()
    {
    }

    /**
     * Test attribute "ris_netw"
     */
    public function testPropertyRisNetw()
    {
    }

    /**
     * Test attribute "ris_kapt"
     */
    public function testPropertyRisKapt()
    {
    }

    /**
     * Test attribute "ris_cards"
     */
    public function testPropertyRisCards()
    {
    }

    /**
     * Test attribute "ris_devices"
     */
    public function testPropertyRisDevices()
    {
    }

    /**
     * Test attribute "ris_emails"
     */
    public function testPropertyRisEmails()
    {
    }

    /**
     * Test attribute "ris_velo"
     */
    public function testPropertyRisVelo()
    {
    }

    /**
     * Test attribute "ris_vmax"
     */
    public function testPropertyRisVmax()
    {
    }

    /**
     * Test attribute "ris_site"
     */
    public function testPropertyRisSite()
    {
    }

    /**
     * Test attribute "ris_device_layers"
     */
    public function testPropertyRisDeviceLayers()
    {
    }

    /**
     * Test attribute "ris_fingerprint"
     */
    public function testPropertyRisFingerprint()
    {
    }

    /**
     * Test attribute "ris_timezone"
     */
    public function testPropertyRisTimezone()
    {
    }

    /**
     * Test attribute "ris_localtime"
     */
    public function testPropertyRisLocaltime()
    {
    }

    /**
     * Test attribute "ris_region"
     */
    public function testPropertyRisRegion()
    {
    }

    /**
     * Test attribute "ris_country"
     */
    public function testPropertyRisCountry()
    {
    }

    /**
     * Test attribute "ris_proxy"
     */
    public function testPropertyRisProxy()
    {
    }

    /**
     * Test attribute "ris_javascript"
     */
    public function testPropertyRisJavascript()
    {
    }

    /**
     * Test attribute "ris_flash"
     */
    public function testPropertyRisFlash()
    {
    }

    /**
     * Test attribute "ris_cookies"
     */
    public function testPropertyRisCookies()
    {
    }

    /**
     * Test attribute "ris_http_country"
     */
    public function testPropertyRisHttpCountry()
    {
    }

    /**
     * Test attribute "ris_language"
     */
    public function testPropertyRisLanguage()
    {
    }

    /**
     * Test attribute "ris_mobile_device"
     */
    public function testPropertyRisMobileDevice()
    {
    }

    /**
     * Test attribute "ris_mobile_type"
     */
    public function testPropertyRisMobileType()
    {
    }

    /**
     * Test attribute "ris_mobile_forwarder"
     */
    public function testPropertyRisMobileForwarder()
    {
    }

    /**
     * Test attribute "ris_voice_device"
     */
    public function testPropertyRisVoiceDevice()
    {
    }

    /**
     * Test attribute "ris_pc_remote"
     */
    public function testPropertyRisPcRemote()
    {
    }

    /**
     * Test attribute "ris_rules_triggered"
     */
    public function testPropertyRisRulesTriggered()
    {
    }

    /**
     * Test attribute "ris_counters_triggered"
     */
    public function testPropertyRisCountersTriggered()
    {
    }

    /**
     * Test attribute "ris_reason_code"
     */
    public function testPropertyRisReasonCode()
    {
    }

    /**
     * Test attribute "ris_ddfs"
     */
    public function testPropertyRisDdfs()
    {
    }

    /**
     * Test attribute "ris_dsr"
     */
    public function testPropertyRisDsr()
    {
    }

    /**
     * Test attribute "ris_uas"
     */
    public function testPropertyRisUas()
    {
    }

    /**
     * Test attribute "ris_browser"
     */
    public function testPropertyRisBrowser()
    {
    }

    /**
     * Test attribute "ris_os"
     */
    public function testPropertyRisOs()
    {
    }

    /**
     * Test attribute "ris_pip_ipad"
     */
    public function testPropertyRisPipIpad()
    {
    }

    /**
     * Test attribute "ris_pip_lat"
     */
    public function testPropertyRisPipLat()
    {
    }

    /**
     * Test attribute "ris_pip_lon"
     */
    public function testPropertyRisPipLon()
    {
    }

    /**
     * Test attribute "ris_pip_country"
     */
    public function testPropertyRisPipCountry()
    {
    }

    /**
     * Test attribute "ris_pip_region"
     */
    public function testPropertyRisPipRegion()
    {
    }

    /**
     * Test attribute "ris_pip_city"
     */
    public function testPropertyRisPipCity()
    {
    }

    /**
     * Test attribute "ris_pip_org"
     */
    public function testPropertyRisPipOrg()
    {
    }

    /**
     * Test attribute "ris_ip_ipad"
     */
    public function testPropertyRisIpIpad()
    {
    }

    /**
     * Test attribute "ris_ip_lat"
     */
    public function testPropertyRisIpLat()
    {
    }

    /**
     * Test attribute "ris_ip_lon"
     */
    public function testPropertyRisIpLon()
    {
    }

    /**
     * Test attribute "ris_ip_country"
     */
    public function testPropertyRisIpCountry()
    {
    }

    /**
     * Test attribute "ris_ip_region"
     */
    public function testPropertyRisIpRegion()
    {
    }

    /**
     * Test attribute "ris_ip_city"
     */
    public function testPropertyRisIpCity()
    {
    }

    /**
     * Test attribute "ris_ip_org"
     */
    public function testPropertyRisIpOrg()
    {
    }

    /**
     * Test attribute "ris_warning_count"
     */
    public function testPropertyRisWarningCount()
    {
    }
}
