<?php
/**
 * ResponseModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KountRISSwaggerV02
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PhpApi;

/**
 * ResponseModelTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseModel
 * @package     PhpApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseModel"
     */
    public function testResponseModel()
    {
    }

    /**
     * Test attribute "get_response"
     */
    public function testPropertyGetResponse()
    {
    }

    /**
     * Test attribute "ris_error_code"
     */
    public function testPropertyRisErrorCode()
    {
    }

    /**
     * Test attribute "ris_version"
     */
    public function testPropertyRisVersion()
    {
    }

    /**
     * Test attribute "ris_mode"
     */
    public function testPropertyRisMode()
    {
    }

    /**
     * Test attribute "ris_transaction_id"
     */
    public function testPropertyRisTransactionId()
    {
    }

    /**
     * Test attribute "ris_merchant_id"
     */
    public function testPropertyRisMerchantId()
    {
    }

    /**
     * Test attribute "ris_session_id"
     */
    public function testPropertyRisSessionId()
    {
    }

    /**
     * Test attribute "ris_order_number"
     */
    public function testPropertyRisOrderNumber()
    {
    }

    /**
     * Test attribute "ris_auto"
     */
    public function testPropertyRisAuto()
    {
    }

    /**
     * Test attribute "ris_reason"
     */
    public function testPropertyRisReason()
    {
    }

    /**
     * Test attribute "ris_reason_code"
     */
    public function testPropertyRisReasonCode()
    {
    }

    /**
     * Test attribute "ris_score"
     */
    public function testPropertyRisScore()
    {
    }

    /**
     * Test attribute "ris_omniscore"
     */
    public function testPropertyRisOmniscore()
    {
    }

    /**
     * Test attribute "ris_geox"
     */
    public function testPropertyRisGeox()
    {
    }

    /**
     * Test attribute "ris_brand"
     */
    public function testPropertyRisBrand()
    {
    }

    /**
     * Test attribute "ris_velo"
     */
    public function testPropertyRisVelo()
    {
    }

    /**
     * Test attribute "ris_vmax"
     */
    public function testPropertyRisVmax()
    {
    }

    /**
     * Test attribute "ris_network"
     */
    public function testPropertyRisNetwork()
    {
    }

    /**
     * Test attribute "ris_know_your_customer"
     */
    public function testPropertyRisKnowYourCustomer()
    {
    }

    /**
     * Test attribute "ris_region"
     */
    public function testPropertyRisRegion()
    {
    }

    /**
     * Test attribute "ris_kaptcha"
     */
    public function testPropertyRisKaptcha()
    {
    }

    /**
     * Test attribute "ris_proxy"
     */
    public function testPropertyRisProxy()
    {
    }

    /**
     * Test attribute "ris_emails"
     */
    public function testPropertyRisEmails()
    {
    }

    /**
     * Test attribute "ris_http_country"
     */
    public function testPropertyRisHttpCountry()
    {
    }

    /**
     * Test attribute "ris_time_zone"
     */
    public function testPropertyRisTimeZone()
    {
    }

    /**
     * Test attribute "ris_cards"
     */
    public function testPropertyRisCards()
    {
    }

    /**
     * Test attribute "ris_pc_remote"
     */
    public function testPropertyRisPcRemote()
    {
    }

    /**
     * Test attribute "ris_devices"
     */
    public function testPropertyRisDevices()
    {
    }

    /**
     * Test attribute "ris_device_layers"
     */
    public function testPropertyRisDeviceLayers()
    {
    }

    /**
     * Test attribute "ris_mobile_forwarder"
     */
    public function testPropertyRisMobileForwarder()
    {
    }

    /**
     * Test attribute "ris_voice_device"
     */
    public function testPropertyRisVoiceDevice()
    {
    }

    /**
     * Test attribute "ris_local_time"
     */
    public function testPropertyRisLocalTime()
    {
    }

    /**
     * Test attribute "ris_mobile_type"
     */
    public function testPropertyRisMobileType()
    {
    }

    /**
     * Test attribute "ris_finger_print"
     */
    public function testPropertyRisFingerPrint()
    {
    }

    /**
     * Test attribute "ris_flash"
     */
    public function testPropertyRisFlash()
    {
    }

    /**
     * Test attribute "ris_language"
     */
    public function testPropertyRisLanguage()
    {
    }

    /**
     * Test attribute "ris_country"
     */
    public function testPropertyRisCountry()
    {
    }

    /**
     * Test attribute "ris_java_script"
     */
    public function testPropertyRisJavaScript()
    {
    }

    /**
     * Test attribute "ris_cookies"
     */
    public function testPropertyRisCookies()
    {
    }

    /**
     * Test attribute "ris_mobile_device"
     */
    public function testPropertyRisMobileDevice()
    {
    }

    /**
     * Test attribute "ris_site"
     */
    public function testPropertyRisSite()
    {
    }

    /**
     * Test attribute "ris_master_card_fraud_score"
     */
    public function testPropertyRisMasterCardFraudScore()
    {
    }

    /**
     * Test attribute "ris_pierced_ip_address"
     */
    public function testPropertyRisPiercedIpAddress()
    {
    }

    /**
     * Test attribute "ris_pierced_ip_address_latitude"
     */
    public function testPropertyRisPiercedIpAddressLatitude()
    {
    }

    /**
     * Test attribute "ris_pierced_ip_address_longitude"
     */
    public function testPropertyRisPiercedIpAddressLongitude()
    {
    }

    /**
     * Test attribute "ris_pierced_ip_address_country"
     */
    public function testPropertyRisPiercedIpAddressCountry()
    {
    }

    /**
     * Test attribute "ris_pierced_ip_address_region"
     */
    public function testPropertyRisPiercedIpAddressRegion()
    {
    }

    /**
     * Test attribute "ris_pierced_ip_address_city"
     */
    public function testPropertyRisPiercedIpAddressCity()
    {
    }

    /**
     * Test attribute "ris_pierced_ip_address_organization"
     */
    public function testPropertyRisPiercedIpAddressOrganization()
    {
    }

    /**
     * Test attribute "ris_ip_address"
     */
    public function testPropertyRisIpAddress()
    {
    }

    /**
     * Test attribute "ris_ip_address_latitude"
     */
    public function testPropertyRisIpAddressLatitude()
    {
    }

    /**
     * Test attribute "ris_ip_address_longitude"
     */
    public function testPropertyRisIpAddressLongitude()
    {
    }

    /**
     * Test attribute "ris_ip_address_country"
     */
    public function testPropertyRisIpAddressCountry()
    {
    }

    /**
     * Test attribute "ris_ip_address_region"
     */
    public function testPropertyRisIpAddressRegion()
    {
    }

    /**
     * Test attribute "ris_ip_address_city"
     */
    public function testPropertyRisIpAddressCity()
    {
    }

    /**
     * Test attribute "ris_ip_address_organization"
     */
    public function testPropertyRisIpAddressOrganization()
    {
    }

    /**
     * Test attribute "ris_date_device_first_seen"
     */
    public function testPropertyRisDateDeviceFirstSeen()
    {
    }

    /**
     * Test attribute "ris_user_agent_string"
     */
    public function testPropertyRisUserAgentString()
    {
    }

    /**
     * Test attribute "ris_device_screen_resolution"
     */
    public function testPropertyRisDeviceScreenResolution()
    {
    }

    /**
     * Test attribute "ris_os"
     */
    public function testPropertyRisOs()
    {
    }

    /**
     * Test attribute "ris_browser"
     */
    public function testPropertyRisBrowser()
    {
    }

    /**
     * Test attribute "ris_to_string"
     */
    public function testPropertyRisToString()
    {
    }

    /**
     * Test attribute "rules_triggered"
     */
    public function testPropertyRulesTriggered()
    {
    }

    /**
     * Test attribute "ris_number_rules_triggered"
     */
    public function testPropertyRisNumberRulesTriggered()
    {
    }

    /**
     * Test attribute "ris_warnings"
     */
    public function testPropertyRisWarnings()
    {
    }

    /**
     * Test attribute "ris_warning_count"
     */
    public function testPropertyRisWarningCount()
    {
    }

    /**
     * Test attribute "ris_errors"
     */
    public function testPropertyRisErrors()
    {
    }

    /**
     * Test attribute "ris_error_count"
     */
    public function testPropertyRisErrorCount()
    {
    }

    /**
     * Test attribute "has_errors"
     */
    public function testPropertyHasErrors()
    {
    }

    /**
     * Test attribute "ris_lexis_nexis_cbd_attributes"
     */
    public function testPropertyRisLexisNexisCbdAttributes()
    {
    }

    /**
     * Test attribute "ris_lexis_nexis_instant_id_attributes"
     */
    public function testPropertyRisLexisNexisInstantIdAttributes()
    {
    }

    /**
     * Test attribute "ris_counters_triggered"
     */
    public function testPropertyRisCountersTriggered()
    {
    }

    /**
     * Test attribute "ris_number_counters_triggered"
     */
    public function testPropertyRisNumberCountersTriggered()
    {
    }

    /**
     * Test attribute "ris_kount_central_customer_id"
     */
    public function testPropertyRisKountCentralCustomerId()
    {
    }

    /**
     * Test attribute "ris_kount_central_warnings"
     */
    public function testPropertyRisKountCentralWarnings()
    {
    }

    /**
     * Test attribute "ris_kount_central_warning_count"
     */
    public function testPropertyRisKountCentralWarningCount()
    {
    }

    /**
     * Test attribute "ris_kount_central_errors"
     */
    public function testPropertyRisKountCentralErrors()
    {
    }

    /**
     * Test attribute "ris_kount_central_error_count"
     */
    public function testPropertyRisKountCentralErrorCount()
    {
    }

    /**
     * Test attribute "ris_kount_central_number_thresholds_triggered"
     */
    public function testPropertyRisKountCentralNumberThresholdsTriggered()
    {
    }

    /**
     * Test attribute "ris_kount_central_decision"
     */
    public function testPropertyRisKountCentralDecision()
    {
    }

    /**
     * Test attribute "kount_central_threshold_events"
     */
    public function testPropertyKountCentralThresholdEvents()
    {
    }
}
