<?php
/**
 * ValuesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * KountRISSwaggerV02
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace PhpApi;

use \PhpApi\Configuration;
use \PhpApi\ApiException;
use \PhpApi\ObjectSerializer;

/**
 * ValuesApiTest Class Doc Comment
 *
 * @category Class
 * @package  PhpApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ValuesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for valuesDelete
     *
     * .
     *
     */
    public function testValuesDelete()
    {
    }

    /**
     * Test case for valuesGet
     *
     * .
     *
     */
    public function testValuesGet()
    {
    }

    /**
     * Test case for valuesGet_0
     *
     * .
     *
     */
    public function testValuesGet0()
    {
    }

    /**
     * Test case for valuesPost
     *
     * .
     *
     */
    public function testValuesPost()
    {
    }

    /**
     * Test case for valuesPut
     *
     * .
     *
     */
    public function testValuesPut()
    {
    }
}
